<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Classes to write multithreading code.</Description>
        <IsPackable>true</IsPackable>
        <Version>10.1.0</Version>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AsyncKeyedLock" Version="$(AsyncKeyedLockVersion)" />
    </ItemGroup>

</Project>
